-- 1. Create a table for the Restaurants (profiles linked to auth.users)
CREATE TABLE public.restaurants (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    location TEXT,
    cuisine_type TEXT,
    capacity INT DEFAULT 50,
    average_rating DECIMAL(3,2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on Row Level Security for restaurants
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;

-- Allow anyone to view restaurants
CREATE POLICY "Public read for restaurants" 
ON public.restaurants 
FOR SELECT USING (true);

-- Allow authenticated users to update their own restaurant profile
CREATE POLICY "Users can update their own restaurant profile" 
ON public.restaurants 
FOR UPDATE USING (auth.uid() = id);

-- Allow inserting profile upon signup via triggers or simple insert
CREATE POLICY "Users can insert their own restaurant profile"
ON public.restaurants
FOR INSERT WITH CHECK (auth.uid() = id);

-- 2. Create a table for the Menus
CREATE TABLE public.menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    items JSONB NOT NULL,
    price DECIMAL(10,2),
    tags TEXT[],
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Turn on Row Level Security for menus
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;

-- Allow anyone to view any menu
CREATE POLICY "Public read for menus" 
ON public.menus 
FOR SELECT USING (true);

-- Allow users to insert menus but only for their own restaurant_id
CREATE POLICY "Restaurants can insert own menus" 
ON public.menus 
FOR INSERT WITH CHECK (auth.uid() = restaurant_id);

-- Allow users to update their own menus
CREATE POLICY "Restaurants can update own menus" 
ON public.menus 
FOR UPDATE USING (auth.uid() = restaurant_id);

-- Allow users to delete their own menus
CREATE POLICY "Restaurants can delete own menus" 
ON public.menus 
FOR DELETE USING (auth.uid() = restaurant_id);

-- 3. Create a table for Customers (end-users of the application, could also be linked to auth.users if they sign up)
CREATE TABLE public.customers (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    preferences TEXT[], -- e.g., ['vegan', 'gluten-free', 'cuchara']
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Customers can view their own profile" 
ON public.customers FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Customers can update their own profile" 
ON public.customers FOR UPDATE USING (auth.uid() = id);

-- 4. Create a table for Reservations / Daily Influx (Crucial for ML demand prediction feedback)
CREATE TABLE public.reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id UUID REFERENCES public.customers(id) ON DELETE SET NULL,
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    menu_id BIGINT REFERENCES public.menus(id) ON DELETE SET NULL,
    reservation_date DATE NOT NULL,
    party_size INT DEFAULT 1,
    status TEXT DEFAULT 'confirmed', -- 'confirmed', 'cancelled', 'completed'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Restaurants can view their own reservations" 
ON public.reservations FOR SELECT USING (auth.uid() = restaurant_id);

CREATE POLICY "Customers can view their own reservations" 
ON public.reservations FOR SELECT USING (auth.uid() = customer_id);

CREATE POLICY "Customers can insert their own reservations" 
ON public.reservations FOR INSERT WITH CHECK (auth.uid() = customer_id);

-- 5. Create a table for ML Predictions Analytics (Stores daily ML recommendations vs Actual)
CREATE TABLE public.daily_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id UUID REFERENCES public.restaurants(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    predicted_menus INT NOT NULL,
    actual_menus_sold INT, -- To be updated at the end of the day for model feedback
    weather_condition TEXT,
    temperature DECIMAL(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(restaurant_id, date)
);

ALTER TABLE public.daily_analytics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Restaurants can view their own analytics" 
ON public.daily_analytics FOR SELECT USING (auth.uid() = restaurant_id);

-- 6. Setup trigger to automatically insert a restaurant row when a user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  -- We assume new signups from the restaurant portal have a specific metadata flag
  -- For generic signups, you might want a customers insert instead, but we'll default to restaurant here for simplicity
  -- based on the current app structure. In a real app, role-based logic or separate metadata is needed.
  IF new.raw_user_meta_data->>'role' = 'restaurant' THEN
    INSERT INTO public.restaurants (id, name, location)
    VALUES (new.id, new.email, 'Sin Ubicación');
  ELSE
    INSERT INTO public.customers (id, full_name)
    VALUES (new.id, split_part(new.email, '@', 1));
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
